import math
import os
from pathlib import Path
import pickle
import sys
import matplotlib.pyplot as plt
import numpy as np
from rich import print
import pandas as pd
from tqdm import tqdm

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from analysis.scripts.utils import compute_energy_metrics
from src.time_expanded_graph.time_expanded_graph import (
    TimeExpandedGraph,
)
from src.constants import DESTINATION_NODES, REPORTS_ROOT, PLOTS_ROOT

plt.rcParams.update({"font.size": 18})
plt.rc("legend", fontsize=14)
plt.rcParams.update({"font.family": "Times New Roman"})

algorithms = [
    ("lls", "LLS_Greedy"),
    ("lls-pat-unaware", "LLS_Greedy (ZRK)"),
    ("lls-mip", "LLS_MIP"),
    ("fcp", "FCP"),
]

report_id = 1773792920
tegs = []
report_dir = os.path.join(REPORTS_ROOT, str(report_id))
plot_dir = os.path.join(PLOTS_ROOT, str(report_id))
os.makedirs(plot_dir, exist_ok=True)
for file_name in os.listdir(report_dir):
    if file_name.endswith(".pkl"):
        file_path = os.path.join(report_dir, file_name)
        match = file_name.split(".")[0].split("_")
        algorithm = match[0]
        scenario = "_".join(match[1:])
        if algorithm not in [alg[0] for alg in algorithms]:
            continue
        with open(file_path, "rb") as f:
            teg: TimeExpandedGraph = pickle.load(f)
        tegs.append((algorithm, scenario, teg))

all_generation = []
all_consumption = []
for algorithm, scenario, teg in tegs:
    should_bypass_retargeting_time = algorithm == "lls-pat-unaware"
    print(
        f"Processing {algorithm} scenario {scenario} with {teg.N} nodes and {teg.K} states..."
    )
    # Initialize metrics storage
    state_metrics_list: list[pd.DataFrame] = []
    accumulated_time = 0
    for state in tqdm(range(teg.K)):
        state_df = pd.DataFrame(
            {
                "state_index": pd.Series(dtype="int64"),
                "tx_node_id": pd.Series(dtype="object"),
                "rx_node_id": pd.Series(dtype="object"),
                "state_duration": pd.Series(dtype="float64"),
                "generated_energy": pd.Series(dtype="float64"),
                "consumed_energy": pd.Series(dtype="float64"),
            }
        )
        for tx_oi_idx in range(teg.N):
            for rx_oi_idx in range(teg.N):
                tx_node_id = teg.nodes[
                    teg.optical_interfaces_to_node[tx_oi_idx]
                ].id
                rx_node_id = teg.nodes[
                    teg.optical_interfaces_to_node[rx_oi_idx]
                ].id

                # If the transmitting node is a destination node,
                # we skip it since it does not generate energy and we are only interested in the energy generated by the source and relay nodes.
                # We can still compute the consumed energy for the destination nodes, but for simplicity we focus on the generated energy for the source and relay nodes.
                if tx_node_id in DESTINATION_NODES:
                    continue
                generated, consumed = compute_energy_metrics(
                    teg,
                    tx_oi_idx,
                    rx_oi_idx,
                    state,
                    teg.graphs[:state],
                    teg.state_durations[state],
                    accumulated_time,
                    tx_node_id,
                    should_bypass_retargeting_time,
                )

                # Add row to state dataframe
                state_df.loc[len(state_df)] = [
                    state,
                    tx_node_id,
                    rx_node_id,
                    teg.state_durations[state],
                    generated,
                    consumed,
                ]
                if teg.graphs[state][tx_oi_idx][rx_oi_idx] != 1:
                    __import__("ipdb").set_trace()

                all_generation.append(generated)
                all_consumption.append(consumed)
        # move the state time pointer
        accumulated_time += teg.state_durations[state]
        # Add state dataframe to total metrics
        state_metrics_list.append(state_df)

    total_metrics_df = [
        state_df.groupby("tx_node_id", as_index=False).agg(
            state_index=("state_index", "first"),
            state_duration=("state_duration", "first"),
            generated_energy=("generated_energy", "first"),
            consumed_energy=("consumed_energy", "sum"),
        )
        for state_df in state_metrics_list
    ]

    rows = []
    for df in total_metrics_df:
        total_generated = df["generated_energy"].sum()
        total_consumed = df["consumed_energy"].sum()

        rows.append(
            {
                "total_time": df["state_duration"].max(),
                "total_generated": total_generated,
                "total_consumed": total_consumed,
                "total_additional_energy": total_generated - total_consumed,
            }
        )

    total_state_metrics = pd.DataFrame(rows)
    total_state_metrics.index.name = "state_index"

    # CSV
    total_state_metrics.to_csv(
        f"{REPORTS_ROOT}/{report_id}/energy_metrics_{algorithm}_{scenario}.csv"
    )

    # PLOT
    total_state_metrics.plot(
        y=["total_generated", "total_consumed", "total_additional_energy"],
        kind="line",
        title=f"Energy Metrics for {algorithm} with {scenario} nodes",
    )
    plt.xlabel("State Index")
    plt.ylabel("Energy (J)")
    plt.grid()
    plt.legend()
    plt.tight_layout()
    plt.savefig(
        f"{PLOTS_ROOT}/{report_id}/energy_metrics_{algorithm}_{scenario}.png"
    )
    plt.close()
    # If we want to globalize the results across all algorithms and node counts.
    # plt.savefig(f"{PLOTS_ROOT}/{algorithm}_{node_count}/energy_metrics_{algorithm}_{node_count}.png")
